#! /bin/bash
yum install nginx git -y
systemctl start nginx
systemctl status nginx
cd /var/www/html
git clone https://github.com/Ironhack-Archive/online-clone-amazon.git
mv online-clone-amazon/* .
tail -f /var/log/httpd/access_log
